export interface VibrationDataModel {
  id: number,
  axMin: number,
  axAvg: number,
  axMax: number,
  ayMin: number,
  ayAvg: number,
  ayMax: number,
  azMin: number,
  azAvg: number,
  azMax: number,
  gxMin: number,
  gxAvg: number,
  gxMax: number,
  gyMin: number,
  gyAvg: number,
  gyMax: number,
  gzMin: number,
  gzAvg: number,
  gzMax: number,
  date: string,
}
